// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ZLYCEZY6gwWWW5tAxHE5o37iYGsQNEk',
    appId: '1:456449790411:web:4d86118743280de9f1a64e',
    messagingSenderId: '456449790411',
    projectId: 'vg-everythingstack',
    authDomain: 'vg-everythingstack.firebaseapp.com',
    storageBucket: 'vg-everythingstack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJohHtFmQTOexRRU2rT5ogqlhgNiBy1o',
    appId: '1:456449790411:android:35d4735d94f52b6ff1a64e',
    messagingSenderId: '456449790411',
    projectId: 'vg-everythingstack',
    storageBucket: 'vg-everythingstack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArv3yUIl-pqReD20iSsn4J9yaEyhkbAEI',
    appId: '1:456449790411:ios:7be517b287bea52ff1a64e',
    messagingSenderId: '456449790411',
    projectId: 'vg-everythingstack',
    storageBucket: 'vg-everythingstack.appspot.com',
    iosClientId:
        '456449790411-9ius15ednupb5tpf1nffbfntkh4cgvae.apps.googleusercontent.com',
    iosBundleId: 'com.everythingstack.xyz',
  );
}
